version: '2'
services:
  asterisk:
    image: andrius/alpine-asterisk
    ports:
      - 5060:5060
      - 5060/udp:5060/udp
      - 5061:5061
      - 5061/udp:5061/udp
    volumes:
      - ./sip.conf:/etc/asterisk/sip.conf
      - ./extensions.conf:/etc/asterisk/extensions.conf
      - ./iax.conf:/etc/asterisk/iax.conf
      - ./voicemail.conf:/etc/asterisk/voicemail.conf
